openapi: 3.0.1
info:
  title: monster-barlgura
  x-cortex-tag: monster-barlgura
  x-cortex-custom-metadata:
    alignment: lawful-evil
    type: fiend
    challenge_rating: 26
    legendary: false
    armor_class: 14
    hit_points: 84
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-barlgura
      alias: github-token-test
